# Generated by Django 2.0.7 on 2019-04-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20190411_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_data',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('files', models.FileField(blank=True, upload_to='')),
                ('category', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
