# Generated by Django 2.0.7 on 2019-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_data_owner1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='owner1',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
