# Generated by Django 2.0.7 on 2019-04-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190412_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
