# Generated by Django 2.0.7 on 2019-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190411_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
