# Generated by Django 2.0.7 on 2019-04-18 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20190416_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmarks',
            fields=[
                ('bookmark_title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bookmark_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project_data')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
