# Generated by Django 2.0.7 on 2019-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='slug',
            field=models.SlugField(default='no'),
            preserve_default=False,
        ),
    ]
