# Generated by Django 2.0.7 on 2019-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.CharField(default='shardulind', max_length=100),
            preserve_default=False,
        ),
    ]
